#ifndef TEST_DATA_INCLUDED
#define TEST_DATA_INCLUDED

const int SAMPLE_SINGLES_SUDOKU_SIZE = 2;
extern const char *SAMPLE_SINGLES_SUDOKU_ARRAY[SAMPLE_SINGLES_SUDOKU_SIZE][2];

#endif // #ifndef TEST_DATA_INCLUDED
